// Build the game-data index from the raw localization dump.
//
// The dump is the game's OWN text, recovered from its resource pack. Every description is a
// TEMPLATE: the numbers are placeholders like {Damage:diff()} resolved against the card's live
// stat, which differs by upgrade. So this yields the EFFECT STRUCTURE for every entity in the
// game - what kind of thing a card does - while the magnitude must come from the observed state.
//
// This is the fix for the largest measured blindness cause: the planner used to know only the
// 159 entities it happened to see in its own runs, and treated every other card as `unsupported`,
// which blanked the whole board's forecast. There are 1,784.
import {readFileSync, writeFileSync, existsSync} from 'node:fs';
import {dirname, join, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const raw = JSON.parse(readFileSync(join(HERE, 'raw-localization.json'), 'utf8'));

// A placeholder tells you the EFFECT and nothing about the magnitude: {Damage:diff()} is the card's
// own damage stat, which changes with upgrade. The token before the colon names the quantity.
const PLACEHOLDER = /\{([A-Za-z][A-Za-z0-9_]*)(?::[^}]*)?\}/g;
const CLEAN = /\[\/?[a-z_ ]+\]|\{[A-Za-z][A-Za-z0-9_]*(?::[^}]*)?\}/g;

const KIND = {
  damage: ['Damage'], block: ['Block'], vulnerable: ['Vulnerable', 'VulnerablePower'],
  weak: ['Weak', 'WeakPower'], strength: ['Strength', 'StrengthPower'],
  dexterity: ['Dexterity', 'DexterityPower'], energy: ['Energy'], cards: ['Cards'],
  heal: ['Heal'], gold: ['Gold'], blockNextTurn: ['BlockNextTurn', 'BlockNextTurnPower'],
  poison: ['Poison', 'PoisonPower'], thorns: ['Thorns', 'ThornsPower'],
  metallicize: ['Metallicize', 'MetallicizePower'], plating: ['Plating', 'PlatingPower'],
  regen: ['Regen', 'RegenPower'], vigor: ['VigorPower'], stars: ['Star', 'Stars'],
};

function classify(text) {
  const effects = {};
  for (const [effect, tokens] of Object.entries(KIND)) {
    for (const t of tokens) {
      if (text.includes(`{${t}`) || text.includes(`{${t}}`)) { (effects[effect] ??= []).push(t); break; }
    }
  }
  for (const m of text.matchAll(PLACEHOLDER)) {
    (effects.placeholders ??= new Set()).add(m[1]);
  }
  if (effects.placeholders) effects.placeholders = [...effects.placeholders].sort();
  return Object.keys(effects).length ? effects : null;
}

const index = {};
for (const [id, entry] of Object.entries(raw)) {
  const description = (entry.description ?? '').replace(CLEAN, ' ').replace(/\s+/g, ' ').trim();
  if (!description && !entry.title) continue;
  index[id] = {
    name: entry.title ?? null,
    lore: entry.lore ?? null,
    // The template is kept verbatim: it is what the game prints, and the planner needs to know a
    // number is a placeholder rather than a value it can use.
    template: entry.description ?? null,
    plain: description || null,
    effects: classify(entry.description ?? ''),
    confidence: entry.description ? 'game-data' : 'title-only',
  };
}

const out = `// GENERATED by spire-demo/gamedata/extract.mjs from the game's own localization.
// Do not hand-edit. ${Object.keys(index).length} entities, recovered from the resource pack.
//
// Descriptions are TEMPLATES. \`{Damage:diff()}\` is the card's own damage stat and changes with
// upgrade, so the template says the EFFECT and never a magnitude. Any number a decision needs must
// come from the observed state; a number read out of a template would be an invented one.
export const GAME_DATA = ${JSON.stringify(index)};

export const GAME_DATA_COUNT = ${Object.keys(index).length};
export const byName = name => GAME_DATA[String(name ?? '').replace(/\\+$/, '').trim().toUpperCase().replace(/[ '\\-]/g, '_')] ?? null;
export default {GAME_DATA, GAME_DATA_COUNT, byName};
`;
writeFileSync(join(HERE, 'game-data.mjs'), out);
console.log(`game-data.mjs: ${Object.keys(index).length} entities, ${Buffer.byteLength(out)} bytes`);
const kinds = {};
for (const v of Object.values(index)) for (const e of Object.keys(v.effects ?? {})) kinds[e] = (kinds[e] ?? 0) + 1;
console.log('effect coverage:', JSON.stringify(kinds));
